/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ModuleInfo, EchelonConfig, CaseStudyItem, KnowledgeNode } from "../types";

export const LAB_MODULES: ModuleInfo[] = [
  // 底层：代数与仿真
  {
    id: "theoretical-algebra",
    number: 1,
    name: "理论代数与建模",
    tier: "algebra-sim",
    tierName: "底层：代数与仿真",
    subtitle: "推导方差放大系数公式，揭示时滞与平滑的指数级放大机制",
    badge: "数学解析",
  },
  {
    id: "system-dynamics",
    number: 6,
    name: "系统动力学仿真",
    tier: "algebra-sim",
    tierName: "底层：代数与仿真",
    subtitle: "基于因果回路与存量流量（Stock-Flow），对长时延震荡进行因果模拟",
    badge: "反馈模拟",
  },

  // 中层：交互与演播
  {
    id: "cascade-sandbox",
    number: 2,
    name: "2D级联沙盒",
    tier: "interaction-playback",
    tierName: "中层：交互与演播",
    subtitle: "拖拽调整终端需求或时滞 L，以 2D 动态波浪演播波幅逐级放大过程",
    badge: "流体波动",
  },
  {
    id: "order-amplification",
    number: 3,
    name: "订单放大演播",
    tier: "interaction-playback",
    tierName: "中层：交互与演播",
    subtitle: "单步解构预测更新、批量订货(Batching)及短缺博弈(Gaming)的微观扭曲",
    badge: "机制分步",
  },
  {
    id: "damping-control",
    number: 4,
    name: "衰减控制演播",
    tier: "interaction-playback",
    tierName: "中层：交互与演播",
    subtitle: "引入 VMI、CPFR 与 POS 实时共享，切片对比策略前后的平抑效果",
    badge: "对策压制",
  },

  // 顶层：实战与决策
  {
    id: "case-studies",
    number: 5,
    name: "四大案例剖析",
    tier: "practice-decision",
    tierName: "顶层：实战与决策",
    subtitle: "深度还原宝洁、沃尔玛、啤酒游戏及华为Mate80真实供应链博弈",
    badge: "工业还原",
  },
  {
    id: "ai-dialogue",
    number: 7,
    name: "AI智能对话窗口",
    tier: "practice-decision",
    tierName: "顶层：实战与决策",
    subtitle: "依托 Gemini 大模型诊断实验异动、根因溯源并给出参数优化对策",
    badge: "科研辅导",
  },
  {
    id: "data-report",
    number: 8,
    name: "数据分析与报告",
    tier: "practice-decision",
    tierName: "顶层：实战与决策",
    subtitle: "多维采集交货率、持有成本与方差放大比，一键生成量化诊断报告",
    badge: "量化审计",
  },
  {
    id: "knowledge-graph",
    number: 9,
    name: "知识导引与图谱",
    tier: "practice-decision",
    tierName: "顶层：实战与决策",
    subtitle: "系统梳理四大成因与经典对策，构建完备的运筹与供应链知识网络",
    badge: "知识图谱",
  },
];

export const ECHELONS: EchelonConfig[] = [
  {
    key: "retailer",
    name: "零售商 (Retailer)",
    shortName: "零售端",
    role: "直接面向终端消费者，接收真实随机需求信号",
    color: "#0d9488", // teal-600
    bgLight: "#f0fdfa",
    borderLight: "#ccfbf1",
  },
  {
    key: "wholesaler",
    name: "批发商 (Wholesaler)",
    shortName: "批发端",
    role: "汇集区域零售商订单，依据安全库存进行补货决策",
    color: "#0284c7", // sky-600
    bgLight: "#f0f9ff",
    borderLight: "#e0f2fe",
  },
  {
    key: "distributor",
    name: "分销商 (Distributor)",
    shortName: "分销枢纽",
    role: "跨区域干线调配与仓储，面临整车拼箱批量考核",
    color: "#4f46e5", // indigo-600
    bgLight: "#eef2ff",
    borderLight: "#e0e7ff",
  },
  {
    key: "manufacturer",
    name: "制造商 (Manufacturer)",
    shortName: "制造工厂",
    role: "工厂总装排产，受制于固定换模节拍与设备产能上限",
    color: "#d97706", // amber-600
    bgLight: "#fffbeb",
    borderLight: "#fef3c7",
  },
  {
    key: "supplier",
    name: "原材料供应商 (Supplier)",
    shortName: "源头材料",
    role: "源头晶圆、塑料粒子、钢铁冶炼，采购周期漫长且资本密集",
    color: "#dc2626", // red-600
    bgLight: "#fef2f2",
    borderLight: "#fee2e2",
  },
];

export const CASE_STUDIES: CaseStudyItem[] = [
  {
    id: "pg-pampers",
    title: "宝洁帮宝适：经典牛鞭效应的发端",
    company: "宝洁公司 (Procter & Gamble)",
    year: "1990s 经典发现",
    industry: "快消日化 (FMCG)",
    summary: "宝洁物流高管在审查婴儿纸尿裤（帮宝适）供应链时震惊地发现：终端婴儿的生理使用率几乎恒定平稳，但在零售、分销、工厂至树脂原料商环节，订单振幅呈现惊人的逐级海啸式发散。",
    symptom: "终端家庭纸尿裤购买量平稳，但原材料供应商接收到的高分子吸水树脂订单月度波动高达 300% 以上，导致工厂产能闲置与加班交替循环。",
    rootCause: "零售商促销后的囤货透支（前瞻性购买）与分销商追求整车满载（FTL）合并订单，叠加坡度预测更新，使信号在向上传递时被严重扭曲。",
    mechanism: [
      "终端婴儿使用平稳：每周每位婴儿约消耗 40-50 片纸尿裤，需求近乎白噪声平稳。",
      "渠道促销与价格折扣：宝洁季度促销促使超市超额进货，促销结束后数周订单跌入冰点。",
      "批量整车运输：分销商为了节省运费，只有积攒满一整卡车才向下单。",
      "工厂与原料厂巨震：上游将偶发的集中订单误判为真实市场爆发，盲目扩大安全储备与原材料采购。",
    ],
    solution: "推行日常平价策略（EDP）减少促销扰动，并与沃尔玛联合启动全球最早的持续补货计划（CRP/VMI），直接抓取 POS 收银机消耗数据驱动生产。",
    impactMetrics: [
      { label: "订单方差放大倍数", before: "8.4x", after: "1.3x", unit: "BWE" },
      { label: "渠道库存周转天数", before: "78 天", after: "26 天", unit: "天" },
      { label: "缺货率", before: "9.2%", after: "1.1%", unit: "%" },
    ],
    quotes: "“婴儿的屁股不会说谎，但层层传递的采购报表却充斥着虚构的狂欢与恐慌。” —— 宝洁供应链复盘笔记",
    tags: ["需求平稳", "价格折让", "FTL整车批量", "CRP协同补货"],
  },
  {
    id: "walmart-edlp",
    title: "沃尔玛天天平价 (EDLP) 与零售革命",
    company: "沃尔玛 (Walmart)",
    year: "1980s - 2000s 战略落地",
    industry: "全球连锁零售巨头",
    summary: "传统零售商热衷于“高-低价跳水式促销”（Hi-Lo Pricing），诱发下游顾客及批发端疯狂囤积与牛鞭效应。沃尔玛通过坚决执行‘天天平价’（Everyday Low Price）从根源斩断价格波动。",
    symptom: "促销期货架一抢而空、配送中心仓库爆仓排队，非促销期门可罗雀、货物积压资金占用，物流成本占比高居不下。",
    rootCause: "价格波动引发前瞻性购买（Forward Buying），采购方依据打折时点而非实际消费节奏集中下达巨额订单。",
    mechanism: [
      "高低定价的恶性循环：价格骤降 -> 需求假性井喷 -> 供应链全负荷透支生产 -> 促销结束降至冰点。",
      "Retail Link 系统联通：将全美数千家门店收银台数据以小时级向供应商透明开放。",
      "交叉转运（Cross-Docking）：干线物流不进库，直接在物流中心分拣台对倒装车，极致压缩提前期 L。",
    ],
    solution: "彻底取缔周期性大减价，常年维持稳定微利价格；全面普及 Retail Link 系统，让供应商自主查看其实时货架库存并承担补货责任（VMI）。",
    impactMetrics: [
      { label: "全链物流成本占营收比", before: "10.5%", after: "5.8%", unit: "%" },
      { label: "货架现货率 (In-stock)", before: "91.0%", after: "98.5%", unit: "%" },
      { label: "供应商预测吻合度", before: "62%", after: "94%", unit: "%" },
    ],
    quotes: "“消除价格震荡，就是消除了供应链中最具破坏力的人造台风。” —— 萨姆·沃尔顿",
    tags: ["天天平价", "Forward Buying", "Cross-Docking", "Retail Link"],
  },
  {
    id: "beer-game",
    title: "MIT 斯隆啤酒分销博弈：人性的系统性误判",
    company: "麻省理工学院斯隆管理学院 (MIT Sloan)",
    year: "1960年由 Jay Forrester 提出",
    industry: "管理科学 / 行为运筹学经典实验",
    summary: "在这个只有 4 个层级（零售商、批发商、分销商、工厂）的极简单品实验中，即便消费者需求仅发生一次从 4 箱到 8 箱的微小台阶式跃升，系统依然必然产生灾难性的欠货风暴与库存崩塌。",
    symptom: "在游戏第 10-15 周全线陷入漫长缺货、积压欠货单（Backlog）；至第 25-30 周订单突然归零，各环节仓库被泛滥成灾的啤酒塞满，总运营成本成倍超标。",
    rootCause: "决策者忽视了在途库存（Pipeline Inventory）与交货时滞（Lead Time Delay），将‘未收到货物’误判为‘订单被遗漏’，因而在恐慌中反复超额补单。",
    mechanism: [
      "初始平衡状态：各级每周需求 4 箱，库存 12 箱，系统稳定运行。",
      "外部阶跃微扰：第 5 周顾客需求微升至 8 箱并保持恒定（仅增加 4 箱）。",
      "时滞陷阱：物料运送需 2 周，信息确认需 2 周，累计时滞 L=4 周。",
      "恐慌倍增：零售商发现库存跌入负数，立刻下达 16 箱甚至 30 箱订单；上级感知到更大缺口，最终工厂制造端订单狂飙至每周 80-100 箱！",
      "过剩清算：几周后滞留路上的天量啤酒全部送达，全线需求却早已饱和，所有人抱头痛惜积压费用。",
    ],
    solution: "实施全链条数据可视化（消除信息墙）、明确区分‘在途库存’与‘在手缺口’，并建立统一节奏的拉动式补货协议。",
    impactMetrics: [
      { label: "最高订单峰值 / 基础需求", before: "12.5x (100箱)", after: "1.1x (8.8箱)", unit: "倍数" },
      { label: "平均单队系统总惩罚费用", before: "$2,840", after: "$310", unit: "美元" },
      { label: "滞后震荡周期", before: "36 周", after: "6 周", unit: "周" },
    ],
    quotes: "“并不是环境制造了混乱，而是人类线性的直觉与多阶时滞的物理世界发生了致命脱节。” —— 彼得·圣吉《第五项修炼》",
    tags: ["MIT啤酒游戏", "在途库存忽略", "滞后性过冲", "系统动力学"],
  },
  {
    id: "huawei-mate80",
    title: "华为高端旗舰供应链：地缘震荡与短缺配额博弈",
    company: "华为技术集成供应链 (Huawei ISC)",
    year: "2023 - 2025 新实战演化",
    industry: "高端消费电子与先进半导体",
    summary: "在外部供应链不可抗力与先进制程芯片产能受限的双重背景下，整机厂商、ODM 组装厂与晶圆/元器件供应商之间爆发了教科书级的‘短缺博弈与恐慌性超额预订’（Phantom Orders）。",
    symptom: "关键元器件交期从 8 周拉长至 40 周以上，渠道黄牛溢价引发终端假性饱和，上游半导体原厂订单排期甚至延伸至 2 年后，但随后消费电子局部疲软引发行业剧烈‘砍单潮’。",
    rootCause: "产能受限时上游采取‘按订货比例配给’（Rationing Allocation），下游厂商为确保拿到 100 万颗芯片，同时向下游 3 家代工厂各下达 200 万颗虚拟订单（虚报率达 200%）。",
    mechanism: [
      "外部冲击与产能吃紧：地缘制约导致关键射频、模拟芯片产能收紧，供需比跌至 60%。",
      "配额分配博弈：上游原厂宣布供货配比为订货量的 50%；采购人员理智地‘多报双倍’以求自保。",
      "虚假繁荣传递：上游晶圆厂被挤爆的虚假排期欺骗，斥巨资启动晶圆厂扩产投资。",
      "潮退挤泡沫：一旦良率攀升或新品发布窗口移转，客户迅速撤销后续订单，供应链面临高额呆滞料减值（E&O Write-down）。",
    ],
    solution: "建立‘阳光配额协议’与阶梯产能定金锁定；引入集成供应链 ISC+ 与基于数字孪生的全流程序列号物料追踪；基于终端激活量而非分销商报单分配芯片配额。",
    impactMetrics: [
      { label: "虚假订单渗透率", before: "45%", after: "4%", unit: "%" },
      { label: "关键器件保供周期", before: "38 周", after: "11 周", unit: "周" },
      { label: "呆滞料跌价准备占营收比", before: "3.2%", after: "0.6%", unit: "%" },
    ],
    quotes: "“在极度短缺中，没有一家企业是单纯的受害者，每一张带有自保性质的虚假订单都是推动海啸的狂风。” —— 现代半导体供应链管理学刊",
    tags: ["短缺配额博弈", "双倍下单", "先进制程半导体", "集成供应链ISC"],
  },
];

export const KNOWLEDGE_NODES: KnowledgeNode[] = [
  {
    id: "cause-forecast",
    category: "cause",
    title: "需求预测更新 (Demand Forecast Updating)",
    subtitle: "成因一：经典信息级联与数学过度修正",
    description: "供应链中每个节点为了确定安全库存与目标库存，都会根据下级订单用平滑算法更新方差与均值。当下游需求增加 10 个单位，为弥补提前期 L 内的累积短缺，上级必须订货 10 + 2L 个单位，导致波动随提前期线性加剧并呈二次方放大。",
    mathFormula: "BWE \\ge 1 + \\frac{2L}{p} + \\frac{2L^2}{p^2}",
    keyAction: "取消中间层级自主预测，全链统一步调，直接读取终端真实 POS 销售流水。",
    relatedIds: ["cause-batching", "remedy-pos", "remedy-leadtime"],
  },
  {
    id: "cause-batching",
    category: "cause",
    title: "订单批量化 (Order Batching)",
    subtitle: "成因二：固定交易成本引发的脉冲冲击",
    description: "为分摊固定订货处理费或获取整车运输（FTL）低运费，企业采用 (s, S) 或 MRP 周期性批量补货策略。在触发点前需求为 0，一旦触发突然释放巨大批量，向上传递时呈现剧烈的离散阶跃。",
    mathFormula: "Q^* = \\sqrt{\\frac{2DS}{H}} \\quad (EOQ经济批量公式)",
    keyAction: "推行 EDI 电子单据降低下单固定成本；推行 Milk-Run 循环拼车取货。",
    relatedIds: ["cause-forecast", "remedy-vmi", "remedy-milkrun"],
  },
  {
    id: "cause-pricing",
    category: "cause",
    title: "价格波动与促销 (Price Fluctuation)",
    subtitle: "成因三：高低跳价诱发的预先购买",
    description: "制造商定期的折让促销、季度返点和批发折扣促使买方进行‘前瞻性购买’（Forward Buying）。买方购买的远超当期消耗，消耗完毕前不再进货，使得真实平稳的需求被人为割裂为波峰与波谷。",
    mathFormula: "Q_{fwd} = D \\cdot \\left[ \\frac{P_{normal} - P_{sale}}{P_{normal} \\cdot I} \\right]",
    keyAction: "实施天天平价（EDLP）策略；改用‘按销售量扫描返利’（Scan-back）替代‘按进货量打折’。",
    relatedIds: ["cause-batching", "remedy-edlp", "case-walmart-edlp"],
  },
  {
    id: "cause-shortage",
    category: "cause",
    title: "短缺博弈 (Rationing & Shortage Gaming)",
    subtitle: "成因四：配给预期下的虚假恐慌订单",
    description: "当产品产能不足或外部突发事件导致供不应求时，供应商通常按订货比例进行配给。下级为了获得所需数量，故意夸大订单量（如需要 100 下单 200）。上级误以为需求井喷盲目扩张，待短缺缓解，天量虚假订单被瞬间撤销。",
    mathFormula: "O_{placed} = \\frac{D_{actual}}{\\min(1, \\; Capacity / \\sum Orders)}",
    keyAction: "按照下游历史实际提货量分配稀缺产能；要求下达订单时缴纳不可退还定金。",
    relatedIds: ["cause-forecast", "remedy-cpfr", "case-huawei-mate80"],
  },
  {
    id: "remedy-pos",
    category: "remedy",
    title: "POS 实时信息共享 (Point-of-Sale Data Sharing)",
    subtitle: "对策一：穿透信息黑箱",
    description: "将最下游零售终端的收银机扫描数据（POS）通过云计算和 EDI 实时穿透给批发商、分销商与制造工厂，使整条供应链看清唯一的真实终端信号，消除各层级重复预测。",
    keyAction: "部署 EDI 与零售商协同看板，用终端流水替换各层级自主推导的订货信号。",
    relatedIds: ["cause-forecast", "remedy-vmi"],
  },
  {
    id: "remedy-vmi",
    category: "remedy",
    title: "供应商管理库存 (Vendor Managed Inventory - VMI)",
    subtitle: "对策二：转移补货决策权",
    description: "由上游供应商直接管理下游客户的仓库或货架库存，供应商依据下游的消耗速度与预设的安全水位主动补货，消除了下游客户自行下单过程中的各种主观扭曲与博弈。",
    keyAction: "签订 VMI 协议与服务水平协议（SLA），由供应方全权负责补库与寄售管理。",
    relatedIds: ["cause-batching", "cause-forecast", "case-pg-pampers"],
  },
  {
    id: "remedy-cpfr",
    category: "remedy",
    title: "协同规划、预测与补货 (CPFR)",
    subtitle: "对策三：单一可信事实源",
    description: "上下游建立深度的商业伙伴协同流程，联合制定销售计划、促销排期与补货方案。当任何一方预测发生显著偏离时触发异常预警机制，共同协商调整，形成‘全链唯一的真实数据’。",
    keyAction: "建立跨组织联合计划工作组，协同审查季节性促销与产能排程。",
    relatedIds: ["cause-shortage", "cause-pricing"],
  },
  {
    id: "remedy-leadtime",
    category: "remedy",
    title: "压缩提前期 (Lead Time Compression / JIT)",
    subtitle: "对策四：斩断二次方放大的根基",
    description: "根据 $BWE \\ge 1 + \\frac{2L}{p} + \\frac{2L^2}{p^2}$，提前期 $L$ 越长，波动放大的二次项越显著。通过精益生产、就近设厂、越库转运（Cross-docking）与敏捷物流将提前期压缩至极限，可直接钝化牛鞭效应。",
    keyAction: "缩短生产准备周期、消除行政报单审批滞后、采用近距离产业集群与循环取货。",
    relatedIds: ["cause-forecast", "cause-batching"],
  },
];
